### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by loelkes** [semuconsulting/semuadmin.octoprint#1]
Hi, I would be interested in taking over the maintenance of this repository.

**Comment by semuadmin** [comment]
Hi @loelkes 

Be my guest. I'd be happy to transfer ownership, though I'd be grateful if you could acknowledge its provenance.

**Comment by loelkes** [comment]
Do you mean that you will remain in the credits (README, LICENSE, ...) as one of the authors? Are you the only author? The commit history is quite short, was it reinitialised from a previous repository?

**Comment by semuadmin** [comment]
> Do you mean that you will remain in the credits (README, LICENSE, ...) as one of the authors? Are you the only author? The commit history is quite short, was it reinitialised from a previous repository?

Essentially, yes, if that's OK. I was the original author (it wasn't based on any previous work) but there have been 4 or 5 relatively minor contributions from others along the way, all of which should be retained in the Git history.

**Comment by loelkes** [comment]
Of course we can keep it that way.

Can you identify the other authors? The git history of this repository only contains four commits, all of which are yours.

**Comment by semuadmin** [comment]
> Of course we can keep it that way.
> 
> Can you identify the other authors? The git history of this repository only contains four commits, all of which are yours.

Ok I must have effectively rebased it a few of months ago - my original repo was created around 5 years ago as far as I can I recall. I used to maintain about 10 Ansible repos at various points over the past 7/8 years or so but have since deleted them all as I no longer had the time.

I'll see if I can dig out the full commit history from an old backup, but I don't think anyone's going to be too precious about it.

Feel free to fork the repo and take it on.

**Comment by loelkes** [comment]
Done.

If you don't want to continue development in this repository, I would recommend either updating the readme to point to the fork and put it in read-only/archive mode, or just deleting it completely.

**Comment by semuadmin** [comment]
All yours.
